### ISSUE TITLE
start Julia REPL error Default.sublime-commands

### ISSUE THREAD

**Issue by AndyYangjd** [PetrKryslUCSD/HowToUseJuliaWithSublimeText3#4]
I write the Default.sublime-commands as your code, but can't start Julia REPL.
But solve the problem after reading the Terminus's README.md.
So the "shell_cmd"  of args in Default.sublime-commands  should be replaced be "cmd "

**Comment by PetrKryslUCSD** [comment]
I don't know. The configuration shown in https://github.com/PetrKryslUCSD/HowToUseJuliaWithSublimeText3#command-to-start-julia-repl
works for me.

**Comment by PetrKryslUCSD** [comment]
What sort of trouble did you have with shell_cmd?

**Comment by AndyYangjd** [comment]
`{
        "caption": "Terminus: Open Julia 1.4",
        "command": "terminus_open",
        "args"   : {
            "cmd": ["D:\\Program Files\\julia\\Julia-1.4.1\\bin\\julia.exe"],
            "cwd": "${file_path:${folder}}",
            "title": "Julia 1.4 REPL",
            "pre_window_hooks": [
                ["focus_group", {"group": 1}]
            ],
            "env": {"JULIA_NUM_THREADS":"2"},       
        }
    },`
At first "shell_cmd" trouble me.
So i read the README.md inTerminus and replace the "shell_cmd" with "cmd", thant all right.

**Comment by PetrKryslUCSD** [comment]
My apologies. I ran out of space in the repository, and my changes were not getting pushed to github. I have corrected the problem, and the repository is now up to date.
The shell command should be like this
```
"shell_cmd": "%LOCALAPPDATA%\\Programs\\Julia\\Julia-1.4.1\\bin\\julia.exe",
```
That is, without the brackets around the command string. Then it works fine.

**Comment by AndyYangjd** [comment]
Thanks for your share.
Besides, i install the LSP for ST3, and find that the auto-formatter work well for julia.

**Comment by PetrKryslUCSD** [comment]
Cool. I'd be interested to hear of your experiences with LSP...

**Comment by PetrKryslUCSD** [comment]
Does the shell command spec work for you. Shall I close this issue?

**Comment by AndyYangjd** [comment]
![图片](https://user-images.githubusercontent.com/44262434/81365624-38b8c880-911b-11ea-986c-867baabe3837.png)
I test the shell_cmd in win10, but not work. The error show above: 
‘D:\Program’ Not an internal or external command, or a runnable program or batch file.

The cmd(not shell_cmd) work well for me

**Comment by AndyYangjd** [comment]
The auto-formattor functon in LSP done well.
I can't realize the Auto-completion in LSP, just like the [link:](https://discourse.julialang.org/t/sublime-text-3-worth-a-look/17142/99?) 
Maybe some configuration is wrong in LSP

**Comment by AndyYangjd** [comment]
The auto-completion in LSP done well after i disable the TabNine and set the auto_complete to true in Preferences.sublime-settings-user.
So it seems that the user must choose one between LSP and TabNine.
@PetrKryslUCSD Maybe this issue should be closed.

**Comment by PetrKryslUCSD** [comment]
Thank you for investigating.

**Comment by AndyYangjd** [comment]
Thanks for your share. Your solution is awesome.
I can't search many information in chinese about how to write julia wite Sublime.
Would your mind i share this repo with the chinese Julia discourse forum?

**Comment by PetrKryslUCSD** [comment]
Of course not, I will be pleased.

**Comment by AndyYangjd** [comment]
Ok, thank you.
