### ISSUE TITLE
How to Debug Julia in Sublime

### ISSUE THREAD

**Issue by jdonnerstag** [PetrKryslUCSD/HowToUseJuliaWithSublimeText3#5]
Thanks a lot for this great set of information. I have 20 years of apps dev experience, but I'm very new to Julia. How does debugging work with Julia + Sublime?  Or more generically: What is your workflow to develop, evaluate and test your Julia code? The Revise package is mentioned in several blogs, but you don't seem to be using it. 

Many thanks a lot for insight

**Comment by PetrKryslUCSD** [comment]
Actually I do use it, but since it has nothing to do with ST I omitted its discussion from the text here.
I use it pretty much as described in the discourse threads that mention Revise.

**Comment by PetrKryslUCSD** [comment]
Sorry, forgot about the debugging: I don't  actually have much use of a debugger. I don't think I've used it once since I started programming Julia. Well, more precisely, since it became available.
